
version: '3.7'
services:
  casino-backend:
    build: .
    image: 10.13.37.7:5000/casino-backend
    networks:
     - bridge
     - enoverlay
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=casino-db
     - MONGO_PORT=27017
     - MONGO_USER=ipv6islove
     - MONGO_PASSWORD=dockerislove
  casino-frontend:
    image: nginx:1.13-alpine
    depends_on:
      - casino-backend
    networks:
      - enoverlay
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=casino-checker"
        - "traefik.docker.network=enoverlay"
        - "traefik.frontend.rule=Host:casino.checker.enowars.com,service12.checker.enowars.com,420.checker.enowars.com"
        - "traefik.port=80"
      replicas: 1
  casino-db:
    image: mongo
    networks:
      - enoverlay
    volumes:
      - casino_db_data:/data/db
#we need to fix the node otherwise the volumes are lost after migration :/
    deploy:
      placement:
        constraints:
          - "node.hostname==blade5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove


networks:
  bridge:
    external: true
  enoverlay:
    external: true
volumes:
  casino_db_data:

    