version: '2.1'
services:
  casino-backend:
    build: .
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:1::2
  casino-frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - casino-backend
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:1::1
networks:
  checkernet:
    external: true
